### ISSUE TITLE
Installing Noise

### ISSUE THREAD

**Issue by idontunderstandcode** [NaN-xyz/Glyph-Filters#42]
I tried what you advised to another user but it doesn't seem to work.

I installed Python 2.7 and pip

`$ pip --version
pip 20.3.4 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)
$ python --version
Python 2.7.18
 `
And did the install for noise

`$ pip install noise
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting noise
  Downloading https://files.pythonhosted.org/packages/18/29/bb830ee6d934311e17a7a4fa1368faf3e73fbb09c0d80fc44e41828df177/noise-1.2.2.tar.gz (125kB)
     |████████████████████████████████| 133kB 1.2MB/s 
Installing collected packages: noise
  Running setup.py install for noise ... done
Successfully installed noise-1.2.2`

But still have this error message on Glyphs (Version 2.6.6)

`Start
Traceback (most recent call last):
  File "Beastly.py", line 8, in <module>
    from NaNGFGraphikshared import *
  File "NaNGFGraphikshared.py", line 13, in <module>
    from NaNGFNoise import roughenLines
  File "NaNGFNoise.py", line 2, in <module>
    from noise import *
ImportError: No module named noise
End`

Same when I try 'import noise' launching the app, I get `Traceback (most recent call last):
  File "<macro>", line 1, in <module>
ImportError: No module named noise`

**Comment by sovichet** [comment]
Are you on Glyphs 2?
You might run into this same issue of mine that the path to python is `/usr/bin/python`.

So if you've installed and used pip from terminal (and most likely installed via homebrew), it will install the `noise` package to a `/usr/local/...` directory. So you need to access the internal python and run this:

```
/usr/bin/python -m pip install --user noise
```

Not sure if it is a recommended way to install, but it seems to be working for me. :-)
