### ISSUE TITLE
Sea Camouflage script not working

### ISSUE THREAD

**Issue by RosaWagner** [NaN-xyz/Glyph-Filters#46]
Error message cc @simoncozens 
```
Traceback (most recent call last):
  File "/Users/rosalie/Google/forks/Glyph-Filters/run-filter.py", line 22, in <module>
    i = importlib.import_module(filter_script)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/SeaCamouflage.py", line 256, in <module>
    SeaCamouflage()
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/SeaCamouflage.py", line 29, in processLayer
    self.SliceGlyph(thislayer, iterations)
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/SeaCamouflage.py", line 72, in SliceGlyph
    G.cut_layer(thislayer, (cutx1, cuty1),(cutx2, cuty2))
  File "/Users/rosalie/Google/forks/Glyph-Filters/NaNGlyphFilters/NaNGlyphsEnvironment.py", line 264, in cut_layer
    raise NotImplementedError
NotImplementedError
```

**Comment by simoncozens** [comment]
Looks like that is a Glyphs API we do not have in glyphsLib (because it's all about cutting up layers into different paths, and we don't need that in glyphsLib). It will be a hard one to implement so the answer might be to run it in Glyphs, not from the command line.

**Comment by RosaWagner** [comment]
Also having the error in Glyphs

```
starting glyph: A
glyph size: M
Traceback (most recent call last):
  File "SeaCamouflage.py", line 256
    SeaCamouflage()
  File "NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "SeaCamouflage.py", line 29, in processLayer
    self.SliceGlyph(thislayer, iterations)
  File "SeaCamouflage.py", line 72, in SliceGlyph
    G.cut_layer(thislayer, (cutx1, cuty1),(cutx2, cuty2))
  File "NaNGlyphsEnvironment.py", line 108, in cut_layer
    layer.cut_between_points(pt1, pt2)
AttributeError: 'NSKVONotifying_GSLayer' object has no attribute 'cut_between_points'
```

**Comment by simoncozens** [comment]
Urgh, should be cutBetweenPoints
