### ISSUE TITLE
Multiple issues when running scripts

### ISSUE THREAD

**Issue by tiagonogueira21** [NaN-xyz/Glyph-Filters#47]
I'm new to Glyphs and scripting but I found out about this cool project and wanted to try it.
I installed Glyphs 2.6.6 and Python 2.7.2 (i had first installed 3.x but I read about it in another issue and changed).
I also installed noise via pip.

I tried to run a first filter (**Spray Paint**) and it worked as expected but when I tried others I kept getting different errors:

**Dirt**
```
Start
starting glyph: I
glyph size: L
Traceback (most recent call last):
  File "Dirt.py", line 78, in <module>
    Dirt()
  File "NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "Dirt.py", line 26, in processLayer
    noisepaths = NoiseOutline(thislayer, outlinedata, noisevars=[0.2, 0, 15])
  File "NaNGFNoise.py", line 78, in NoiseOutline
    x_noiz = pnoise1( (n+seedx)*noisescale, 3) 
  File "NaNGFNoise.py", line 37, in pnoise1
    total += _noise1(x * freq, repeat * freq, base) * amp
  File "NaNGFNoise.py", line 19, in _noise1
    i = (i & 255) + base
TypeError: unsupported operand type(s) for &: 'float' and 'int'
End
```

**Storm**
```
Start
starting glyph: I
glyph size: L
Traceback (most recent call last):
  File "Storm.py", line 36, in <module>
    Storm()
  File "NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "Storm.py", line 33, in processLayer
    operateOnBlackAtInterval(thislayer, self.drawStorm, self.gridsize)
  File "NaNGFGraphikshared.py", line 177, in operateOnBlackAtInterval
    if not withinLayerBlack(layer, x, y):
  File "NaNGFGraphikshared.py", line 167, in withinLayerBlack
    return (len(intersections) % 2) == 1
TypeError: object of type 'NoneType' has no len()
End
```

**Glitch**
```
Start
starting glyph: I
glyph size: L
Traceback (most recent call last):
  File "Glitch.py", line 74, in <module>
    Glitch()
  File "NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "Glitch.py", line 35, in processLayer
    slicedpaths = self.returnSlicedPaths(paths, self.sliceheight)
  File "Glitch.py", line 55, in returnSlicedPaths
    G.cut_layer(tmplayer, (ox-1, y), (ox+w+1, y))
  File "NaNGlyphsEnvironment.py", line 108, in cut_layer
    layer.cut_between_points(pt1, pt2)
AttributeError: 'GSLayer' object has no attribute 'cut_between_points'
End
```

What am I missing?
Thanks

**Comment by tiagonogueira21** [comment]
**update:** i noticed that [this issue](https://github.com/NaN-xyz/Glyph-Filters/issues/46#issuecomment-1790896726) had the same error as the Glitch one, so I went ahead and replaced 'cut_between_points'. I still get errors though:
```
Start
starting glyph: A
glyph size: L
Traceback (most recent call last):
  File "Glitch.py", line 74, in <module>
    Glitch()
  File "NaNFilter.py", line 25, in __init__
    self.processGlyph(glyph)
  File "NaNFilter.py", line 45, in processGlyph
    self.processLayer(thislayer, params)
  File "Glitch.py", line 36, in processLayer
    self.ShiftPathsNoise(slicedpaths, maxshift)
  File "Glitch.py", line 69, in ShiftPathsNoise
    y_noiz = pnoise1( ((1000+n)+seedy)*noisescale, 3) 
NameError: global name 'pnoise1' is not defined
End
```

**Comment by tiagonogueira21** [comment]
any help? 🙏 @NaN-xyz @simoncozens
